jobs:
  - name: runshscriptaccess1331
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      - IN: trigger-dv
      #- IN: yyyryt
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
        # - script: https://github.com/shiphitchcock4/sample-script
    flags: www3454
         
  - name: testdup2mani
    type: manifest
    steps:
      - IN: new-image123
     # - IN: t111
    flags: weee345
     
  - name: runShitnoaccess
    type: runSh
 #   allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd     
     
  - name: runcliaccess
    type: runCLI
   # allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd   
         
  - name: runcliaccess12345
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd     

  - name: nodependecy
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      - IN: trigger-dv
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
        # - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd     
