jobs:
  - name: runshscriptaccess1331
    type: runSh
    on_start:
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      - IN: trigger-dv
     # - IN: state
      - IN: newssh
      #- IN: notify-hipchat
      
      #- IN: yyyryt
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         - script: printenv
         #- script: echo 'test'
        # - script: https://github.com/shiphitchcock4/sample-script
         - script: echo "integration name------>-"$NEWSSH_NAME
         - script: echo "public key------>-"$NEWSSH_INTEGRATION_PUBLICKEY
         - script: echo "private key----->-"$NEWSSH_INTEGRATION_PRIVATEKEY
         - script: echo "public key path----->-"$NEWSSH_PUBLIC_KEY_PATH
         - script: echo "private key path------->-"$NEWSSH_PRIVATE_KEY_PATH
         
         - script: echo "integration name------>-"$NOTIFYHIPCHAT_NAME
        # - script: echo "public key------>-"$NEWSSH_INTEGRATION_PUBLICKEY
        # - script: echo "private key----->-"$NEWSSH_INTEGRATION_PRIVATEKEY
        # - script: echo "public key path----->-"$NEWSSH_PUBLIC_KEY_PATH
        # - script: echo "private key path------->-"$NEWSSH_PRIVATE_KEY_PATH 
    
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
 
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    flags: www3454
         
  - name: testdup2mani
    type: manifest
    on_start:
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    allowPublicAccess: true
    steps:
      - IN: new-image123
     # - IN: t111
     
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
 
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    flags: weee345
     
  - name: runShitnoaccess
    type: runSh
 #   allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd     
    always:
      - script: echo "This works on_always"
      #- NOTIFY: notify-slack
      - NOTIFY: newemail
      - NOTIFY: notify-hipchat
    #  - NOTIFY: notify-irc
  - name: runcliaccess
    type: runCLI
   # allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
    #  - IN: state
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
         - script: echo 'api'
         - script: echo 'test'
      - OUT: state
         #- script: pwd   
         
  - name: runcliaccess12345
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      #- IN: t111
      - TASK:
         - script: ./IN/sampletestRepo1/gitRepo/echo.sh
         - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd     

  - name: nodependecy
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: sampletestRepo1edit
      - IN: trigger-dv
      - TASK:
         - script: ./IN/sampletestRepo1edit/gitRepo/echo.sh
        # - script: echo 'api'
         #- script: echo 'test'
         #- script: pwd    
         
         
         
  - name: deploy_ddc
    type: deploy    
    on_start:
    
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
    
    steps:      
      - IN: testdup2mani
      - IN: ddc_cluster
     # - IN: ddc_dopts
      #- IN: t2runsh
      - TASK: managed
    flags: deploy_ddc
    on_success:         
   
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676 
      - NOTIFY: notify-hipchat
    on_failure:
      - NOTIFY: newemail
      - NOTIFY: emailtestordersort1235676
      - NOTIFY: notify-hipchat
     
